### ISSUE TITLE
Fix cloudinary api to ensure posts and stories functionality works

### ISSUE THREAD

**Issue by detective-sokka** [detective-sokka/Travelgram#2]

**Comment by detectivesokka** [comment]
Pushed fix directly to main branch in [this commit](https://github.com/detective-sokka/Travelgram/commit/ea6abbf11ef9ed9980e4a0302017b283c4cd4086)

**Comment by detective-sokka** [comment]
Pushed fix directly to main branch in [this commit](https://github.com/detective-sokka/Travelgram/commit/ea6abbf11ef9ed9980e4a0302017b283c4cd4086)
