### ISSUE TITLE
Improve UI using tailwind

### ISSUE THREAD

**Issue by detective-sokka** [detective-sokka/Travelgram#5]

**Comment by jakepears** [comment]
i'll do it, assign to me plz

**Comment by detective-sokka** [comment]
Sure @jakepears. Feel free to contact me if you have any doubts

**Comment by jakepears** [comment]
just curious, is there any reason you chose to many divide server and client instead of using a framwork to make life a bit easier?

**Comment by detective-sokka** [comment]
I was forced to use React and Node.js by my professor. Cheers!
